import ThemeColors from '@/theme/colors';

const Colors = {
  light: {
    background: ThemeColors.background,
    surface: ThemeColors.surface,
    surfaceSecondary: ThemeColors.surfaceSecondary,
    surfaceTertiary: ThemeColors.surfaceTertiary,
    text: ThemeColors.text,
    textSecondary: ThemeColors.textSecondary,
    textTertiary: ThemeColors.textTertiary,
    accent: ThemeColors.accent,
    accentLight: ThemeColors.accentLight,
    teal: ThemeColors.accentSoft,
    tealLight: ThemeColors.accentSoftLight,
    border: ThemeColors.border,
    borderLight: ThemeColors.borderLight,
    tint: ThemeColors.accent,
    tabIconDefault: ThemeColors.tabInactive,
    tabIconSelected: ThemeColors.tabActive,
    star: ThemeColors.star,
    danger: ThemeColors.danger,
    dangerLight: ThemeColors.dangerLight,
    success: ThemeColors.success,
    successLight: ThemeColors.successLight,
    overlay: ThemeColors.overlay,
    skeleton: ThemeColors.skeleton,
    warm: ThemeColors.warm,
    warmLight: ThemeColors.warmLight,
    pink: ThemeColors.pinkAccent,
    pinkLight: ThemeColors.pinkLight,
    deepAccent: ThemeColors.deepAccent,
    deepAccentLight: ThemeColors.deepAccentLight,
    brick: ThemeColors.brickAccent,
    brickLight: ThemeColors.brickLight,
    emerald: ThemeColors.emerald,
    copper: ThemeColors.copper,
    indigo: ThemeColors.indigo,
    beige: ThemeColors.beige,
    softGreen: ThemeColors.softGreen,
  },
};

export default Colors;
