import C from '@/theme/colors';

const Colors = {
  light: {
    background: C.background,
    surface: C.surface,
    surfaceSecondary: C.surface,
    surfaceTertiary: C.glass,
    text: C.text,
    textSecondary: C.textSecondary,
    textTertiary: C.textMuted,
    accent: C.accent,
    accentLight: C.accentSoft,
    teal: C.accent,
    tealLight: C.accentSoft,
    border: C.surfaceBorder,
    borderLight: C.glassBorder,
    tint: C.accent,
    tabIconDefault: C.tabInactive,
    tabIconSelected: C.tabActive,
    star: C.star,
    danger: C.danger,
    dangerLight: C.dangerBg,
    success: C.accent,
    successLight: C.accentSoft,
    overlay: C.overlay,
    skeleton: C.surface,
    warm: C.gold,
    warmLight: C.accentSoft,
    pink: C.velvet,
    pinkLight: C.dangerBg,
    deepAccent: C.gold,
    deepAccentLight: C.accentSoft,
    brick: C.velvet,
    brickLight: C.dangerBg,
    emerald: C.accent,
    copper: C.gold,
    indigo: C.textMuted,
    beige: C.cream,
    softGreen: C.accent,
  },
};

export default Colors;
